name: 24x7 Telegram Bot Runner

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'   # Har 5 ghante mein yeh workflow automatic dobara chalu ho jayega
  workflow_dispatch:        # Isse tum manual bhi click karke chalu kar sakte ho

concurrency:
  group: telegram-bot
  cancel-in-progress: true  # Purana run cancel karke naya chalata hai, taaki 2 bot instance ek saath na chalein

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 340    # 5 ghante 40 minute baad yeh band hone se pehle naya trigger karega

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests[socks] pynacl python-socks async_timeout

    - name: Run Telegram Bot
      env:
        API_ID: 32569415
        API_HASH: 4209968745cb99d37820d5ba7b4845bd
        BOT_TOKEN: 8918032442:AAF4kZgCz7ZMC8eAfcpr-f1qr4bTjfs_YyI
      run: |
        echo "Bot is starting 24x7 inside GitHub Actions..."
        python main.py
